/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kamac8665
 */
public class FormDevelopingSoftwareforPlanetZirboin extends javax.swing.JFrame {

    /**
     * Creates new form FormDevelopingSoftwareforPlanetZirboin
     */
    public FormDevelopingSoftwareforPlanetZirboin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgrundPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        infoBackgroundPanel = new javax.swing.JPanel();
        infoLabel1 = new javax.swing.JLabel();
        infoLabel2 = new javax.swing.JLabel();
        infoLabel3 = new javax.swing.JLabel();
        infoLabel4 = new javax.swing.JLabel();
        vrobitInput = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        equivilenceLabel = new javax.swing.JLabel();
        drobitsLabel = new javax.swing.JLabel();
        clickwicksLabel = new javax.swing.JLabel();
        gazoontightsLabel = new javax.swing.JLabel();
        frazointsLabel = new javax.swing.JLabel();
        blointointsLabel = new javax.swing.JLabel();
        vrobitsLabel = new javax.swing.JLabel();
        drobzit = new javax.swing.JLabel();
        clickwick = new javax.swing.JLabel();
        gazoontight = new javax.swing.JLabel();
        frazoint = new javax.swing.JLabel();
        blointoint = new javax.swing.JLabel();
        vrobits = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgrundPanel.setBackground(new java.awt.Color(153, 153, 255));

        titleLabel.setFont(new java.awt.Font("Stylus BT", 3, 18)); // NOI18N
        titleLabel.setText("Alien Bank");

        inputLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        inputLabel.setText("Amount of Vrobits to exchange:");

        infoLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        infoLabel1.setText("Please input the amount of ");

        infoLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        infoLabel2.setText("Vrobits you would like to");

        infoLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        infoLabel3.setText("exchange for the least");

        infoLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        infoLabel4.setText("amount of coins.");

        javax.swing.GroupLayout infoBackgroundPanelLayout = new javax.swing.GroupLayout(infoBackgroundPanel);
        infoBackgroundPanel.setLayout(infoBackgroundPanelLayout);
        infoBackgroundPanelLayout.setHorizontalGroup(
            infoBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoBackgroundPanelLayout.createSequentialGroup()
                .addGroup(infoBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel3)
                    .addComponent(infoLabel4)
                    .addComponent(infoLabel2))
                .addGap(14, 14, 14))
            .addComponent(infoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        infoBackgroundPanelLayout.setVerticalGroup(
            infoBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel2)
                .addGap(4, 4, 4)
                .addComponent(infoLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel4)
                .addContainerGap())
        );

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        equivilenceLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        equivilenceLabel.setText("That amount is equivient to:");

        drobitsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        drobitsLabel.setText("Drobzits:");

        clickwicksLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        clickwicksLabel.setText("Clickwicks:");

        gazoontightsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        gazoontightsLabel.setText("Gazoontights:");

        frazointsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        frazointsLabel.setText("Frazoints:");

        blointointsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        blointointsLabel.setText("Blointoints:");

        vrobitsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vrobitsLabel.setText("Vrobits:");

        drobzit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        drobzit.setText("0");

        clickwick.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        clickwick.setText("0");

        gazoontight.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        gazoontight.setText("0");

        frazoint.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        frazoint.setText("0");

        blointoint.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        blointoint.setText("0");

        vrobits.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vrobits.setText("0");

        javax.swing.GroupLayout backgrundPanelLayout = new javax.swing.GroupLayout(backgrundPanel);
        backgrundPanel.setLayout(backgrundPanelLayout);
        backgrundPanelLayout.setHorizontalGroup(
            backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgrundPanelLayout.createSequentialGroup()
                .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgrundPanelLayout.createSequentialGroup()
                        .addComponent(infoBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vrobitInput)
                            .addGroup(backgrundPanelLayout.createSequentialGroup()
                                .addComponent(enterButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(backgrundPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgrundPanelLayout.createSequentialGroup()
                        .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(equivilenceLabel)
                            .addGroup(backgrundPanelLayout.createSequentialGroup()
                                .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drobitsLabel)
                                    .addComponent(clickwicksLabel)
                                    .addComponent(gazoontightsLabel)
                                    .addComponent(frazointsLabel)
                                    .addComponent(blointointsLabel)
                                    .addComponent(vrobitsLabel))
                                .addGap(50, 50, 50)
                                .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drobzit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clickwick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gazoontight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(frazoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(blointoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(vrobits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(148, 248, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgrundPanelLayout.setVerticalGroup(
            backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgrundPanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgrundPanelLayout.createSequentialGroup()
                        .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgrundPanelLayout.createSequentialGroup()
                                .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputLabel)
                                    .addComponent(vrobitInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enterButton))
                            .addComponent(infoBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(equivilenceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgrundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drobitsLabel)
                            .addComponent(drobzit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clickwick)
                        .addGap(4, 4, 4)
                        .addComponent(gazoontight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frazoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blointoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vrobits))
                    .addGroup(backgrundPanelLayout.createSequentialGroup()
                        .addComponent(clickwicksLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gazoontightsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frazointsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blointointsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vrobitsLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        int numVrobits;
        int numDrobzit;
        int numClickwick;
        int numGazoontight;
        int numFrazoint;
        int numBlointoint;
        int remainingVrobit;
        
        numVrobits = Integer.parseInt(vrobitInput.getText());
        
        numDrobzit = numVrobits / 100000;
        drobzit.setText("" + numDrobzit);
        
        numVrobits = numVrobits % 100000;
        
        numClickwick = numVrobits / 50000;
        clickwick.setText("" + numClickwick);
        
        numVrobits = numVrobits % 50000;
        
        numGazoontight = numVrobits / 10000;
        gazoontight.setText("" + numGazoontight);
        
        numVrobits = numVrobits % 10000;
        
        numFrazoint = numVrobits / 1000;
        frazoint.setText("" + numFrazoint);
        
        numVrobits = numVrobits % 1000;
        
        numBlointoint = numVrobits / 500;
        blointoint.setText("" + numBlointoint);
        
        remainingVrobit = numVrobits % 500;
        vrobits.setText("" + remainingVrobit);
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDevelopingSoftwareforPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDevelopingSoftwareforPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDevelopingSoftwareforPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDevelopingSoftwareforPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDevelopingSoftwareforPlanetZirboin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgrundPanel;
    private javax.swing.JLabel blointoint;
    private javax.swing.JLabel blointointsLabel;
    private javax.swing.JLabel clickwick;
    private javax.swing.JLabel clickwicksLabel;
    private javax.swing.JLabel drobitsLabel;
    private javax.swing.JLabel drobzit;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel equivilenceLabel;
    private javax.swing.JLabel frazoint;
    private javax.swing.JLabel frazointsLabel;
    private javax.swing.JLabel gazoontight;
    private javax.swing.JLabel gazoontightsLabel;
    private javax.swing.JPanel infoBackgroundPanel;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel infoLabel3;
    private javax.swing.JLabel infoLabel4;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField vrobitInput;
    private javax.swing.JLabel vrobits;
    private javax.swing.JLabel vrobitsLabel;
    // End of variables declaration//GEN-END:variables
}
